# fly.toml app configuration file generated for cinecalidad-stremio-addon on 2025-08-13T15:10:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cinecalidad-stremio-addon'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
