[build]
  publish = "."
  command = "pnpm install --no-frozen-lockfile && pnpm start"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
